# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Alice in kernel land"
email: timstert23@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog from a low level enthusiast.
  You can expect explanations about low level concepts and
  general low level / osdev talk.
  The name "Alice in kernel land" is a dub on alice in wonderland.
  It's my tribute to the wonders of kernels and operating systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://v01d-null.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: V01D-NULL
github: V01D-NULL

header_image: assets/profile.png

google_analytics:
comments: true
disqus: purelog-jekyll

author: Tim Thompson
author_bio: >-
  Hey there, I hope you enjoyed this blog post!
  My name is Tim, I am an 18 year young developer who has a particular interest
  in low level development. My favorite dev tools? Nothing more than vscode, ubunutu,
  C + x86 assembly and a cup of tea :^)
  Education: None actually, I'm still in my senior year of highschool, aiming high for
  a CE degree though!
  Check my github if you haven't already, and I'll see you in the next post.
  Bye!
author_pic: https://v01d-null.github.io/assets/profile-sm.png
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Tim Thompson
      avatar: assets/profile-sm.png
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: journal-entry
      content-type: journals

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title
  notes:
    output: true
    permalink: /notes/:title
  journals:
    output: true
    permalink: /journals/:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
